sonar.projectKey=Yael-Authier_proyecto-integrador-5
sonar.organization=yael-authier

sonar.projectName=proyecto-integrador-5
sonar.projectVersion=1.0

sonar.sources=src,app
sonar.exclusions=venv/**,notebooks/**,data/**,models/**,__pycache__/**

sonar.sourceEncoding=UTF-8